version: "3.7"
services:
  fpm:
    container_name: php_fpm_container
    build: # Info to build the Docker image
      context: ./docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # environment:
    #   # XDEBUG_MODE: debug
    #   # XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000


    volumes:
      - ./:/var/www/project/:cached # Location of the project for php-fpm. Note this should be the same for NGINX.*
  nginx:
    container_name: nginx_container
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 8080:80 


  database:
    container_name: mysql_container
    image: mysql:8.0.31

    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: cloud-erp
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: test
    ports:
        - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql


volumes:
  persistent:

